module PaletteList exposing
    ( paletteList
    , p16Metallic, aNiceRoom, autumnBerry, blackwhitered, camo2, cloods, elveneight, galacticGreens, hidingInTheWildflowers, hypnospaceColorPalette, juiciful8, lavendertown, libra8, magicMoon, messy12, moondrom, oceansSeven, playful28, pokemonDppPoketchBlue, pokemonDppPoketchGreen, pokemonDppPoketchOrange, pokemonDppPoketchPurple, pokemonDppPoketchRed, pokemonDppPoketchTurquoise, pokemonDppPoketchWhite, pokemonDppPoketchYellow, rabbit5am, runesSpells, smoky09, superSpark, tyAbruptHorror2, tyAbruptHorror4, tyBleu8, tyDisasterGirl20, tyMonsterDungeons11, tyMonsterDungeons16, tyNightLight5, tyPsygnosia26, tySeedOfDespair10, wanted21
    )

{-| The comprehensive list of Lospec palettes
This file is automatically generated weekly.

@docs paletteList

The list of all palettes follows. There's a lot of them!
If you need a specific one, it's probably easier to check the official list
<https://lospec.com/palette-list>

@docs p16Metallic, aNiceRoom, autumnBerry, blackwhitered, camo2, cloods, elveneight, galacticGreens, hidingInTheWildflowers, hypnospaceColorPalette, juiciful8, lavendertown, libra8, magicMoon, messy12, moondrom, oceansSeven, playful28, pokemonDppPoketchBlue, pokemonDppPoketchGreen, pokemonDppPoketchOrange, pokemonDppPoketchPurple, pokemonDppPoketchRed, pokemonDppPoketchTurquoise, pokemonDppPoketchWhite, pokemonDppPoketchYellow, rabbit5am, runesSpells, smoky09, superSpark, tyAbruptHorror2, tyAbruptHorror4, tyBleu8, tyDisasterGirl20, tyMonsterDungeons11, tyMonsterDungeons16, tyNightLight5, tyPsygnosia26, tySeedOfDespair10, wanted21

-}

import Color exposing (rgb255)
import Dict exposing (Dict)
import Palette exposing (Palette, createPalette)


{-| 16-Metallic by Sansh
<https://lospec.com/palette-list/16-metallic>
-}
p16Metallic : Palette.Palette
p16Metallic =
    createPalette "16-Metallic" [ rgb255 250 186 248, rgb255 83 68 89, rgb255 49 18 144, rgb255 23 15 26, rgb255 255 255 255, rgb255 134 108 133, rgb255 39 72 147, rgb255 51 11 17, rgb255 181 233 212, rgb255 129 189 230, rgb255 56 119 197, rgb255 86 29 37, rgb255 252 231 120, rgb255 200 143 73, rgb255 164 86 42, rgb255 151 58 53 ] [ "16", "brass", "challenge", "gold", "metallic", "restrictive", "saturated", "silver", "vibrant" ] (Just "Sansh") "https://lospec.com/palette-list/16-metallic"


{-| A nice room by Rekotti
<https://lospec.com/palette-list/a-nice-room>
-}
aNiceRoom : Palette.Palette
aNiceRoom =
    createPalette "A nice room" [ rgb255 21 20 26, rgb255 255 240 167, rgb255 236 202 101, rgb255 219 152 86, rgb255 202 255 173, rgb255 152 229 143, rgb255 84 171 129, rgb255 47 125 125, rgb255 232 147 121, rgb255 212 97 97, rgb255 234 187 134, rgb255 201 134 95, rgb255 72 72 125, rgb255 58 58 102, rgb255 184 211 242, rgb255 38 38 56, rgb255 81 88 112 ] [ "yellowandblue" ] (Just "Rekotti") "https://lospec.com/palette-list/a-nice-room"


{-| Autumn Berry by RosePrince
<https://lospec.com/palette-list/autumn-berry>
-}
autumnBerry : Palette.Palette
autumnBerry =
    createPalette "Autumn Berry" [ rgb255 117 14 27, rgb255 99 46 52, rgb255 159 83 78, rgb255 156 102 59, rgb255 64 96 76, rgb255 141 168 121, rgb255 191 180 113, rgb255 131 88 138, rgb255 123 53 87 ] [ "autumn", "green", "muted", "purple", "red", "yellow" ] (Just "RosePrince") "https://lospec.com/palette-list/autumn-berry"


{-| Black,White,Red by SolidFrog
<https://lospec.com/palette-list/blackwhitered>
-}
blackwhitered : Palette.Palette
blackwhitered =
    createPalette "Black,White,Red" [ rgb255 28 22 38, rgb255 254 255 251, rgb255 255 41 97 ] [] (Just "SolidFrog") "https://lospec.com/palette-list/blackwhitered"


{-| Camo2 by CorniferSleeps
<https://lospec.com/palette-list/camo2>
-}
camo2 : Palette.Palette
camo2 =
    createPalette "Camo2" [ rgb255 215 209 134, rgb255 76 89 69 ] [ "1bit", "2colours", "simple" ] (Just "CorniferSleeps") "https://lospec.com/palette-list/camo2"


{-| cloods by technicolor
<https://lospec.com/palette-list/cloods>
-}
cloods : Palette.Palette
cloods =
    createPalette "cloods" [ rgb255 17 34 51, rgb255 255 255 17 ] [ "cloud", "clouds" ] (Just "technicolor") "https://lospec.com/palette-list/cloods"


{-| Elven\_Eight by CorniferSleeps
<https://lospec.com/palette-list/elveneight>
-}
elveneight : Palette.Palette
elveneight =
    createPalette "Elven_Eight" [ rgb255 253 144 170, rgb255 254 233 207, rgb255 228 200 165, rgb255 245 255 151, rgb255 148 255 155, rgb255 148 232 253, rgb255 77 73 74, rgb255 225 145 252 ] [ "bright", "fantasy", "rainbow" ] (Just "CorniferSleeps") "https://lospec.com/palette-list/elveneight"


{-| Galactic Greens by Gsus Of Suburbia
<https://lospec.com/palette-list/galactic-greens>
-}
galacticGreens : Palette.Palette
galacticGreens =
    createPalette "Galactic Greens" [ rgb255 232 241 166, rgb255 202 214 112, rgb255 163 194 85, rgb255 111 163 65, rgb255 73 143 69, rgb255 56 116 80, rgb255 45 92 86, rgb255 31 55 65, rgb255 30 32 41, rgb255 22 22 28 ] [ "green" ] (Just "Gsus Of Suburbia") "https://lospec.com/palette-list/galactic-greens"


{-| Hiding in the wildflowers by Tofu
<https://lospec.com/palette-list/hiding-in-the-wildflowers>
-}
hidingInTheWildflowers : Palette.Palette
hidingInTheWildflowers =
    createPalette "Hiding in the wildflowers" [ rgb255 125 28 60, rgb255 201 48 56, rgb255 222 106 56, rgb255 255 173 59, rgb255 247 139 139, rgb255 230 92 133, rgb255 204 51 137, rgb255 137 28 110, rgb255 74 16 54, rgb255 15 8 16, rgb255 9 32 18, rgb255 17 58 28, rgb255 23 85 21, rgb255 50 103 25, rgb255 81 124 31, rgb255 124 146 30, rgb255 175 172 28, rgb255 252 249 96, rgb255 70 152 109, rgb255 62 140 118, rgb255 43 113 70, rgb255 90 98 218, rgb255 48 140 229, rgb255 56 158 236, rgb255 64 175 243, rgb255 85 195 245, rgb255 110 218 249, rgb255 146 228 246, rgb255 184 240 242, rgb255 205 255 237, rgb255 252 255 247 ] [ "bright", "cartoon", "clouds", "happy", "pink", "sunny" ] (Just "Tofu") "https://lospec.com/palette-list/hiding-in-the-wildflowers"


{-| Hypnospace Color Palette by jordon porcenaluk
<https://lospec.com/palette-list/hypnospace-color-palette>
-}
hypnospaceColorPalette : Palette.Palette
hypnospaceColorPalette =
    createPalette "Hypnospace Color Palette" [ rgb255 20 20 20, rgb255 91 90 101, rgb255 123 131 131, rgb255 235 228 221, rgb255 49 36 84, rgb255 137 74 211, rgb255 182 130 255, rgb255 213 203 251, rgb255 149 46 138, rgb255 191 74 212, rgb255 15 47 95, rgb255 0 109 143, rgb255 143 181 245, rgb255 154 239 255, rgb255 137 144 245, rgb255 153 164 244, rgb255 154 199 245, rgb255 16 158 61, rgb255 158 199 34, rgb255 173 208 116, rgb255 237 224 109, rgb255 255 176 3, rgb255 2 207 155, rgb255 108 185 154, rgb255 87 255 188, rgb255 133 77 57, rgb255 191 53 75, rgb255 232 73 44, rgb255 235 112 68, rgb255 209 137 127, rgb255 241 167 149 ] [ "game", "hypnospace", "internet", "retro" ] (Just "jordon porcenaluk") "https://lospec.com/palette-list/hypnospace-color-palette"


{-| Juiciful-8 by Zenit40
<https://lospec.com/palette-list/juiciful-8>
-}
juiciful8 : Palette.Palette
juiciful8 =
    createPalette "Juiciful-8" [ rgb255 255 247 244, rgb255 255 198 198, rgb255 255 130 130, rgb255 255 47 78, rgb255 198 10 95, rgb255 130 10 95, rgb255 66 10 66, rgb255 2 2 2 ] [ "fruit", "juiciful8", "pink", "purple", "raspberry" ] (Just "Zenit40") "https://lospec.com/palette-list/juiciful-8"


{-| LavenderTown by graytones
<https://lospec.com/palette-list/lavendertown>
-}
lavendertown : Palette.Palette
lavendertown =
    createPalette "LavenderTown" [ rgb255 30 12 81, rgb255 44 41 140, rgb255 113 85 198, rgb255 173 107 223, rgb255 226 135 222, rgb255 252 188 232 ] [ "lavender", "soft" ] (Just "graytones") "https://lospec.com/palette-list/lavendertown"


{-| LIBRA-8 by Solitaire
<https://lospec.com/palette-list/libra-8>
-}
libra8 : Palette.Palette
libra8 =
    createPalette "LIBRA-8" [ rgb255 86 70 94, rgb255 142 55 133, rgb255 192 67 148, rgb255 231 174 67, rgb255 205 205 116, rgb255 126 168 129, rgb255 241 237 215, rgb255 255 181 135 ] [ "green", "orange", "purple", "yellow" ] (Just "Solitaire") "https://lospec.com/palette-list/libra-8"


{-| Magic Moon by RosePrince
<https://lospec.com/palette-list/magic-moon>
-}
magicMoon : Palette.Palette
magicMoon =
    createPalette "Magic Moon" [ rgb255 142 171 200, rgb255 104 125 203, rgb255 118 56 189, rgb255 146 25 157, rgb255 154 87 180, rgb255 242 94 147, rgb255 245 146 172, rgb255 250 179 144, rgb255 251 201 185, rgb255 251 253 182 ] [ "blue", "orange", "pink", "purple", "sky", "sunset" ] (Just "RosePrince") "https://lospec.com/palette-list/magic-moon"


{-| messy 12 by \_Simy\_
<https://lospec.com/palette-list/messy-12>
-}
messy12 : Palette.Palette
messy12 =
    createPalette "messy 12" [ rgb255 255 26 178, rgb255 255 36 36, rgb255 251 127 9, rgb255 253 255 118, rgb255 94 247 76, rgb255 9 122 57, rgb255 8 255 168, rgb255 87 86 172, rgb255 71 0 120, rgb255 32 9 34, rgb255 82 96 103, rgb255 235 238 215 ] [] (Just "_Simy_") "https://lospec.com/palette-list/messy-12"


{-| moondrom by Paratroopa
<https://lospec.com/palette-list/moondrom>
-}
moondrom : Palette.Palette
moondrom =
    createPalette "moondrom" [ rgb255 42 36 43, rgb255 70 64 64, rgb255 119 91 91, rgb255 204 112 72, rgb255 215 181 80, rgb255 104 168 171, rgb255 144 213 156, rgb255 255 255 178 ] [ "8bits", "arcade", "contrast", "mint", "moon", "planet", "space" ] (Just "Paratroopa") "https://lospec.com/palette-list/moondrom"


{-| Ocean's Seven by MaximusTheSpacepirate
<https://lospec.com/palette-list/oceans-seven>
-}
oceansSeven : Palette.Palette
oceansSeven =
    createPalette "Ocean's Seven" [ rgb255 0 0 0, rgb255 26 28 44, rgb255 41 54 111, rgb255 59 93 201, rgb255 65 166 246, rgb255 115 239 247, rgb255 244 244 244 ] [] (Just "MaximusTheSpacepirate") "https://lospec.com/palette-list/oceans-seven"


{-| Playful 28 by M1K3\_dev
<https://lospec.com/palette-list/playful-28>
-}
playful28 : Palette.Palette
playful28 =
    createPalette "Playful 28" [ rgb255 255 25 71, rgb255 217 22 87, rgb255 196 20 117, rgb255 173 17 145, rgb255 143 94 67, rgb255 120 79 56, rgb255 102 67 48, rgb255 89 59 42, rgb255 237 255 97, rgb255 235 218 89, rgb255 237 195 90, rgb255 237 169 90, rgb255 135 255 147, rgb255 93 227 156, rgb255 56 209 166, rgb255 26 186 149, rgb255 31 203 255, rgb255 48 176 255, rgb255 71 142 255, rgb255 89 122 255, rgb255 255 56 162, rgb255 224 49 184, rgb255 201 44 196, rgb255 154 42 191, rgb255 242 255 252, rgb255 209 255 246, rgb255 189 255 242, rgb255 153 255 235 ] [ "28", "playful", "playful28", "saturated" ] (Just "M1K3_dev") "https://lospec.com/palette-list/playful-28"


{-| Pokémon DPP Pokétch - Blue by Sylfare
<https://lospec.com/palette-list/pokemon-dpp-poketch-blue>
-}
pokemonDppPoketchBlue : Palette.Palette
pokemonDppPoketchBlue =
    createPalette "Pokémon DPP Pokétch - Blue" [ rgb255 138 138 251, rgb255 65 81 186, rgb255 56 56 105, rgb255 16 24 32 ] [ "blue", "ds", "nintendo", "pokemon", "poketch" ] (Just "Sylfare") "https://lospec.com/palette-list/pokemon-dpp-poketch-blue"


{-| Pokémon DPP Pokétch - green by Sylfare
<https://lospec.com/palette-list/pokemon-dpp-poketch-green>
-}
pokemonDppPoketchGreen : Palette.Palette
pokemonDppPoketchGreen =
    createPalette "Pokémon DPP Pokétch - green" [ rgb255 113 178 113, rgb255 81 130 81, rgb255 56 81 48, rgb255 16 40 24 ] [ "ds", "green", "nintendo", "pokemon", "poketch" ] (Just "Sylfare") "https://lospec.com/palette-list/pokemon-dpp-poketch-green"


{-| Pokémon DPP Pokétch - orange by Sylfare
<https://lospec.com/palette-list/pokemon-dpp-poketch-orange>
-}
pokemonDppPoketchOrange : Palette.Palette
pokemonDppPoketchOrange =
    createPalette "Pokémon DPP Pokétch - orange" [ rgb255 195 146 105, rgb255 138 97 56, rgb255 81 65 40, rgb255 40 32 16 ] [ "ds", "nintendo", "orange", "pokemon", "poketch" ] (Just "Sylfare") "https://lospec.com/palette-list/pokemon-dpp-poketch-orange"


{-| Pokémon DPP Pokétch - Purple by Sylfare
<https://lospec.com/palette-list/pokemon-dpp-poketch-purple>
-}
pokemonDppPoketchPurple : Palette.Palette
pokemonDppPoketchPurple =
    createPalette "Pokémon DPP Pokétch - Purple" [ rgb255 162 113 178, rgb255 121 81 130, rgb255 73 48 81, rgb255 32 16 32 ] [ "ds", "nintendo", "pokemon", "poketch", "purple" ] (Just "Sylfare") "https://lospec.com/palette-list/pokemon-dpp-poketch-purple"


{-| Pokémon DPP Pokétch - Red by Sylfare
<https://lospec.com/palette-list/pokemon-dpp-poketch-red>
-}
pokemonDppPoketchRed : Palette.Palette
pokemonDppPoketchRed =
    createPalette "Pokémon DPP Pokétch - Red" [ rgb255 219 113 113, rgb255 170 73 73, rgb255 97 32 32, rgb255 32 16 16 ] [ "ds", "nintendo", "pokemon", "poketch", "red" ] (Just "Sylfare") "https://lospec.com/palette-list/pokemon-dpp-poketch-red"


{-| Pokémon DPP Pokétch - Turquoise by Sylfare
<https://lospec.com/palette-list/pokemon-dpp-poketch-turquoise>
-}
pokemonDppPoketchTurquoise : Palette.Palette
pokemonDppPoketchTurquoise =
    createPalette "Pokémon DPP Pokétch - Turquoise" [ rgb255 89 186 195, rgb255 32 130 138, rgb255 16 89 97, rgb255 32 24 8 ] [ "ds", "nintendo", "pokemon", "poketch", "turquoise" ] (Just "Sylfare") "https://lospec.com/palette-list/pokemon-dpp-poketch-turquoise"


{-| Pokémon DPP Pokétch - White by Sylfare
<https://lospec.com/palette-list/pokemon-dpp-poketch-white>
-}
pokemonDppPoketchWhite : Palette.Palette
pokemonDppPoketchWhite =
    createPalette "Pokémon DPP Pokétch - White" [ rgb255 162 162 162, rgb255 121 121 121, rgb255 81 81 81, rgb255 24 24 24 ] [ "ds", "nintendo", "pokemon", "poketch", "white" ] (Just "Sylfare") "https://lospec.com/palette-list/pokemon-dpp-poketch-white"


{-| Pokémon DPP Pokétch - yellow by Sylfare
<https://lospec.com/palette-list/pokemon-dpp-poketch-yellow>
-}
pokemonDppPoketchYellow : Palette.Palette
pokemonDppPoketchYellow =
    createPalette "Pokémon DPP Pokétch - yellow" [ rgb255 186 178 113, rgb255 130 130 65, rgb255 73 81 48, rgb255 32 32 16 ] [ "ds", "nintendo", "pokemon", "poketch", "yellow" ] (Just "Sylfare") "https://lospec.com/palette-list/pokemon-dpp-poketch-yellow"


{-| RABBIT5AM by RABBITKING
<https://lospec.com/palette-list/rabbit5am>
-}
rabbit5am : Palette.Palette
rabbit5am =
    createPalette "RABBIT5AM" [ rgb255 255 247 247, rgb255 255 227 200, rgb255 137 170 203, rgb255 99 64 101 ] [ "2bit", "4color", "gameboy" ] (Just "RABBITKING") "https://lospec.com/palette-list/rabbit5am"


{-| Runes & Spells by Signore Socket
<https://lospec.com/palette-list/runes-spells>
-}
runesSpells : Palette.Palette
runesSpells =
    createPalette "Runes & Spells" [ rgb255 0 4 18, rgb255 217 185 130 ] [ "1bit", "ancient", "magic", "norse", "runes", "witch" ] (Just "Signore Socket") "https://lospec.com/palette-list/runes-spells"


{-| smoky 09 by green guy
<https://lospec.com/palette-list/smoky-09>
-}
smoky09 : Palette.Palette
smoky09 =
    createPalette "smoky 09" [ rgb255 250 250 250, rgb255 212 216 224, rgb255 172 172 172, rgb255 145 139 140, rgb255 107 97 94, rgb255 59 52 46, rgb255 36 33 26, rgb255 14 13 10, rgb255 3 2 1 ] [ "brown", "dark", "gray", "grey", "monoramp", "muted", "smoke", "unsaturated" ] (Just "green guy") "https://lospec.com/palette-list/smoky-09"


{-| Super-Spark by ANoob
<https://lospec.com/palette-list/super-spark>
-}
superSpark : Palette.Palette
superSpark =
    createPalette "Super-Spark" [ rgb255 25 24 28, rgb255 87 96 125, rgb255 149 153 132, rgb255 232 237 236, rgb255 240 180 127, rgb255 191 117 191, rgb255 184 99 110, rgb255 85 79 105, rgb255 82 98 161, rgb255 123 188 232, rgb255 92 133 89, rgb255 116 194 97 ] [ "12", "anoob", "artist", "desaturated", "superspark" ] (Just "ANoob") "https://lospec.com/palette-list/super-spark"


{-| TY - Abrupt Horror 2 by Toby\_Yasha
<https://lospec.com/palette-list/ty-abrupt-horror-2>
-}
tyAbruptHorror2 : Palette.Palette
tyAbruptHorror2 =
    createPalette "TY - Abrupt Horror 2" [ rgb255 149 161 125, rgb255 74 65 38 ] [ "1bit" ] (Just "Toby_Yasha") "https://lospec.com/palette-list/ty-abrupt-horror-2"


{-| TY - Abrupt Horror 4 by Toby\_Yasha
<https://lospec.com/palette-list/ty-abrupt-horror-4>
-}
tyAbruptHorror4 : Palette.Palette
tyAbruptHorror4 =
    createPalette "TY - Abrupt Horror 4" [ rgb255 176 208 112, rgb255 143 161 108, rgb255 114 110 78, rgb255 83 75 71 ] [] (Just "Toby_Yasha") "https://lospec.com/palette-list/ty-abrupt-horror-4"


{-| TY - Bleu 8 by Toby\_Yasha
<https://lospec.com/palette-list/ty-bleu-8>
-}
tyBleu8 : Palette.Palette
tyBleu8 =
    createPalette "TY - Bleu 8" [ rgb255 210 219 178, rgb255 172 162 143, rgb255 135 103 113, rgb255 95 85 109, rgb255 118 187 141, rgb255 70 130 130, rgb255 64 64 109, rgb255 42 39 36 ] [] (Just "Toby_Yasha") "https://lospec.com/palette-list/ty-bleu-8"


{-| TY - Disaster Girl 20 by Toby\_Yasha
<https://lospec.com/palette-list/ty-disaster-girl-20>
-}
tyDisasterGirl20 : Palette.Palette
tyDisasterGirl20 =
    createPalette "TY - Disaster Girl 20" [ rgb255 205 190 172, rgb255 123 125 106, rgb255 66 90 88, rgb255 60 59 74, rgb255 104 114 187, rgb255 107 94 130, rgb255 96 72 77, rgb255 99 58 53, rgb255 53 47 40, rgb255 42 37 42, rgb255 8 4 0, rgb255 197 164 107, rgb255 203 119 79, rgb255 159 103 62, rgb255 120 92 59, rgb255 74 71 51, rgb255 118 162 177, rgb255 78 141 102, rgb255 81 104 62, rgb255 38 52 51 ] [ "dark", "darkfantasy", "depressing", "dungeon", "dungeoncrawler", "fantasy", "medieval", "retro" ] (Just "Toby_Yasha") "https://lospec.com/palette-list/ty-disaster-girl-20"


{-| TY - Monster Dungeons 11 by Toby\_Yasha
<https://lospec.com/palette-list/ty-monster-dungeons-11>
-}
tyMonsterDungeons11 : Palette.Palette
tyMonsterDungeons11 =
    createPalette "TY - Monster Dungeons 11" [ rgb255 143 191 213, rgb255 131 133 207, rgb255 118 85 162, rgb255 49 58 145, rgb255 205 147 115, rgb255 177 72 99, rgb255 145 49 49, rgb255 237 230 200, rgb255 128 128 120, rgb255 72 84 84, rgb255 55 58 62 ] [ "crawler", "dungeon", "dungeoncrawler", "game", "monster", "rpg" ] (Just "Toby_Yasha") "https://lospec.com/palette-list/ty-monster-dungeons-11"


{-| TY - Monster Dungeons 16 by Toby\_Yasha
<https://lospec.com/palette-list/ty-monster-dungeons-16>
-}
tyMonsterDungeons16 : Palette.Palette
tyMonsterDungeons16 =
    createPalette "TY - Monster Dungeons 16" [ rgb255 143 191 213, rgb255 131 133 207, rgb255 118 85 162, rgb255 49 58 145, rgb255 205 147 115, rgb255 177 72 99, rgb255 145 49 49, rgb255 167 116 52, rgb255 120 66 51, rgb255 52 49 29, rgb255 102 172 125, rgb255 74 120 51, rgb255 237 230 200, rgb255 128 128 120, rgb255 72 84 84, rgb255 55 58 62 ] [ "crawler", "dungeon", "dungeoncrawler", "game", "monster", "rpg" ] (Just "Toby_Yasha") "https://lospec.com/palette-list/ty-monster-dungeons-16"


{-| TY - Night Light 5 by Toby\_Yasha
<https://lospec.com/palette-list/ty-night-light-5>
-}
tyNightLight5 : Palette.Palette
tyNightLight5 =
    createPalette "TY - Night Light 5" [ rgb255 219 185 154, rgb255 186 148 80, rgb255 99 90 84, rgb255 51 51 64, rgb255 24 32 41 ] [] (Just "Toby_Yasha") "https://lospec.com/palette-list/ty-night-light-5"


{-| TY - Psygnosia 26 by Toby\_Yasha
<https://lospec.com/palette-list/ty-psygnosia-26>
-}
tyPsygnosia26 : Palette.Palette
tyPsygnosia26 =
    createPalette "TY - Psygnosia 26" [ rgb255 119 120 91, rgb255 115 97 80, rgb255 82 82 76, rgb255 68 63 65, rgb255 27 30 41, rgb255 0 0 0, rgb255 42 34 42, rgb255 54 39 71, rgb255 90 66 86, rgb255 100 100 124, rgb255 158 164 167, rgb255 203 199 173, rgb255 64 49 141, rgb255 81 108 191, rgb255 121 194 201, rgb255 203 232 247, rgb255 0 51 8, rgb255 8 74 60, rgb255 84 106 0, rgb255 78 141 102, rgb255 114 187 80, rgb255 62 43 34, rgb255 162 50 78, rgb255 162 99 47, rgb255 224 139 121, rgb255 224 201 121 ] [ "psygnosia" ] (Just "Toby_Yasha") "https://lospec.com/palette-list/ty-psygnosia-26"


{-| TY - Seed of Despair 10 by Toby\_Yasha
<https://lospec.com/palette-list/ty-seed-of-despair-10>
-}
tySeedOfDespair10 : Palette.Palette
tySeedOfDespair10 =
    createPalette "TY - Seed of Despair 10" [ rgb255 167 162 123, rgb255 172 129 95, rgb255 135 117 103, rgb255 110 100 63, rgb255 94 74 64, rgb255 127 141 139, rgb255 130 135 85, rgb255 114 114 95, rgb255 82 70 88, rgb255 71 83 75 ] [] (Just "Toby_Yasha") "https://lospec.com/palette-list/ty-seed-of-despair-10"


{-| Wanted21 by skeddles
<https://lospec.com/palette-list/wanted21>
-}
wanted21 : Palette.Palette
wanted21 =
    createPalette "Wanted21" [ rgb255 255 236 189, rgb255 255 233 166, rgb255 255 219 143, rgb255 250 207 122, rgb255 247 188 105, rgb255 237 169 92, rgb255 225 138 80, rgb255 208 122 71, rgb255 174 97 56, rgb255 116 70 49, rgb255 82 55 43, rgb255 54 39 25, rgb255 116 76 63, rgb255 186 107 72, rgb255 211 124 80, rgb255 231 144 85, rgb255 249 166 94, rgb255 115 82 54, rgb255 143 106 64, rgb255 183 139 78, rgb255 225 164 93 ] [ "map", "old", "orange", "paper", "sepia", "yellow" ] (Just "skeddles") "https://lospec.com/palette-list/wanted21"


{-| All the Lospec color palettes, in a useful Dict format.

If you only need to use one or two specific palettes, you should use the function names instead to keep asset sizes small

Palettes.elm contains some functions that can help search through this structure

-}
paletteList : Dict String Palette
paletteList =
    Dict.fromList
        [ ( "16-metallic", p16Metallic )
        , ( "a-nice-room", aNiceRoom )
        , ( "autumn-berry", autumnBerry )
        , ( "blackwhitered", blackwhitered )
        , ( "camo2", camo2 )
        , ( "cloods", cloods )
        , ( "elveneight", elveneight )
        , ( "galactic-greens", galacticGreens )
        , ( "hiding-in-the-wildflowers", hidingInTheWildflowers )
        , ( "hypnospace-color-palette", hypnospaceColorPalette )
        , ( "juiciful-8", juiciful8 )
        , ( "lavendertown", lavendertown )
        , ( "libra-8", libra8 )
        , ( "magic-moon", magicMoon )
        , ( "messy-12", messy12 )
        , ( "moondrom", moondrom )
        , ( "oceans-seven", oceansSeven )
        , ( "playful-28", playful28 )
        , ( "pokemon-dpp-poketch-blue", pokemonDppPoketchBlue )
        , ( "pokemon-dpp-poketch-green", pokemonDppPoketchGreen )
        , ( "pokemon-dpp-poketch-orange", pokemonDppPoketchOrange )
        , ( "pokemon-dpp-poketch-purple", pokemonDppPoketchPurple )
        , ( "pokemon-dpp-poketch-red", pokemonDppPoketchRed )
        , ( "pokemon-dpp-poketch-turquoise", pokemonDppPoketchTurquoise )
        , ( "pokemon-dpp-poketch-white", pokemonDppPoketchWhite )
        , ( "pokemon-dpp-poketch-yellow", pokemonDppPoketchYellow )
        , ( "rabbit5am", rabbit5am )
        , ( "runes-spells", runesSpells )
        , ( "smoky-09", smoky09 )
        , ( "super-spark", superSpark )
        , ( "ty-abrupt-horror-2", tyAbruptHorror2 )
        , ( "ty-abrupt-horror-4", tyAbruptHorror4 )
        , ( "ty-bleu-8", tyBleu8 )
        , ( "ty-disaster-girl-20", tyDisasterGirl20 )
        , ( "ty-monster-dungeons-11", tyMonsterDungeons11 )
        , ( "ty-monster-dungeons-16", tyMonsterDungeons16 )
        , ( "ty-night-light-5", tyNightLight5 )
        , ( "ty-psygnosia-26", tyPsygnosia26 )
        , ( "ty-seed-of-despair-10", tySeedOfDespair10 )
        , ( "wanted21", wanted21 )
        ]
